# Builds the site. Run from the repo root: python tools/build_pages.py
# 1. Merges assets/src/<level>/*.js (one lesson per file) and _words.js into assets/data/<level>.js
# 2. Writes every HTML page.
# Site-specific settings live in tools/site_config.py; this file is identical in HSK-Learning and Korean-Learning.
import io, json, os, sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from site_config import V, BRAND, SEAL, FOOTER, SITE_JS, SITE_HEAD, H1, LEAD, LEVEL_LEAD, LEVELS  # noqa: E402


def read(path):
    with io.open(path, encoding="utf-8") as f:
        return f.read()


def write(path, text):
    os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
    with io.open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)


# ---------- 1. merge lesson sources ----------
counts = {}
for key, label, d, _ in LEVELS:
    src = os.path.join("assets", "src", key)
    meta = json.loads(read(os.path.join(src, "_level.json")))
    out = ["// Generated by tools/build_pages.py from assets/src/%s. Edit the source files, not this one." % key,
           "window.HSK = window.HSK || {};",
           "window.HSK.%s = %s;" % (key, json.dumps(dict(meta, lessons=[]), ensure_ascii=False))]
    lessons = sorted(f for f in os.listdir(src) if f.endswith(".js") and not f.startswith("_"))
    for f in lessons:
        out.append("window.HSK.%s.lessons.push(%s);" % (key, read(os.path.join(src, f)).strip().rstrip(";")))
    words = os.path.join(src, "_words.js")
    if os.path.exists(words):
        out.append("window.HSK.%s.words = %s;" % (key, read(words).strip().rstrip(";")))
    write(os.path.join("assets", "data", key + ".js"), "\n".join(out) + "\n")
    counts[key] = len(lessons)


# ---------- 2. pages ----------
def page(prefix, title, body, scripts=True, levels=None):
    tags = ""
    if scripts:
        keys = [k for k, *_ in LEVELS] if levels is None else levels
        tags = "".join('<script src="%sassets/data/%s.js?v=%d"></script>' % (prefix, k, V) for k in keys)
        tags += SITE_JS + '<script src="%sassets/app.js?v=%d"></script>' % (prefix, V)
    return """<!doctype html>
<html lang="nl">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{title}</title>
<link rel="stylesheet" href="{p}assets/style.css?v={v}">
{head}
</head>
<body data-root="{p}">
<header class="site"><div class="wrap">
  <a class="brand" href="{p}index.html"><span class="seal">{seal}</span><span class="name">{brand}</span></a>
  <nav><a href="{p}index.html#niveaus" data-nav="leren">Leren</a><a href="{p}herhaling.html" data-nav="herhalen">Herhalen <span class="count" data-due></span></a><a href="{p}documentatie.html" data-nav="grammatica">Grammatica</a><a href="{p}documentatie.html#woorden" data-nav="woorden">Woorden</a></nav>
  <a class="btn cta" href="{p}index.html#niveaus" data-continue>Ga verder</a>
</div></header>
<main class="wrap">
{body}
<footer>{footer}</footer>
</main>
{tags}</body></html>
""".format(head=SITE_HEAD, footer=FOOTER, seal=SEAL, brand=BRAND, title=title, p=prefix, v=V, body=body.strip(), tags=tags)


home_data = "<script>window.HOME = %s;</script>" % json.dumps(
    {"h1": H1, "lead": LEAD, "topics": {k: t for k, _, _, t in LEVELS}}, ensure_ascii=False)
fallback = "".join('<li><a href="%s/">%s</a></li>' % (d, label) for _, label, d, _ in LEVELS)
write("index.html", page("", BRAND, """
<div id="app" data-page="home"><h1>%s</h1><p class="lead">%s</p><ul>%s</ul></div>
%s
""" % (H1, LEAD, fallback, home_data)))

write("herhaling.html", page("", "Herhalen · " + BRAND, '<div id="app" data-page="review"><p>Laden...</p></div>'))
write("documentatie.html", page("", "Documentatie · " + BRAND, '<div id="app" data-page="docs"><p>Laden...</p></div>'))

for key, label, d, _ in LEVELS:
    write(d + "/index.html", page("../", label + " · " + BRAND, """
<h1>%s</h1>
<p class="lead">%s</p>
<div id="app" data-page="level" data-level="%s"><p>Laden...</p></div>
""" % (label, LEVEL_LEAD, key)))
    write(d + "/les.html", page("../", "Les · " + label, """
<div id="app" data-page="lesson" data-level="%s"><p>Laden...</p><noscript>Deze les heeft JavaScript nodig.</noscript></div>
""" % key))
    write(d + "/woorden.html", page("../", "Woorden · " + label, """
<div id="app" data-page="words" data-level="%s"><p>Laden...</p></div>
""" % key, levels=[key]))
print("built v=%d: %s" % (V, ", ".join("%s %d" % kv for kv in counts.items())))
